module.exports = {
  DISTRIBUTION_CREATION_FAILED: "Unable to create Cloudfront distribution.",
  DISTRIBUTION_DELETED: "Distribution successfully deleted:\n",
  DISTRIBUTION_DELETION_FAILED: "unable to delete distribution",
  DISTRIBUTION_NONEXISTENT: "Distribution not found.",
  DISTRIBUTION_UPDATED: "Distribution successfully updated:\n",
  DISTRIBUTION_UPDATE_FAILED: "unable to update distribution",
  ZERO_STRING: "0",
  DEFAULT_ROOT_OBJECT: "index.html",
  ORIGINS_QUANTITY: "1",
  FORWARD_SLASH: "/",
  EMPTY_STRING: "",
  BUCKET_PREFIX: "S3-",
  PRICE_CLASS: "PriceClass_100",
  COMMENT: "Jolt",
  COOKIE_FORWARD: "all",
  TIME_TO_LIVE: "300",
  VIEWER_PROTOCOL_POLICY: "allow-all",
  HTTP_METHODS: ["GET", "HEAD", "OPTIONS", "PUT", "PATCH", "POST", "DELETE"],
  ONE_STRING: "1",
  FUNCTIONS_PATH_PATTERN: ".functions/*",
  LAMBDA_EVENT_TYPE: "viewer-request",
};
